spring:
  application:
    name: Remedy

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: ${POSTGRE_URL}
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASSWORD}


server:
  servlet:
    context-path: /api/v1

jwt:
  access-time: ${access-time}
  refresh-time: ${refresh-time}
  prefix: ${prefix}
  header: ${header}
  secret-key: ${secret-key}

logging:
  level:
    web: info
