spring:
  application:
    name: Remedy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: ${MONGO_URI}

  elasticsearch:
    uris: ${ELASTICSEARCH_URL}
    connection-timeout: 10s
    socket-timeout: 60s

server:
  servlet:
    context-path: /api/v1

jwt:
  access-time: ${access-time}
  refresh-time: ${refresh-time}
  prefix: ${prefix}
  header: ${header}
  secret-key: ${secret-key}

minio:
  minio-url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  default-bucket: ${DEFAULT_BUCKET}

logging:
  level:
    web: info
